vsync = false
frame = "transparent"
title-hidden = true

[font]
size = 19
edging = "subpixelantialias"
hinting = "slight"

[[font.normal]]
family = "CommitMono"
style = "W275"

# You can set a different font for fallback
[[font.normal]]
family = "Fira Code Light"
style = "Normal"

[[font.bold]]
family = "CommitMono"
style = "W500"

[font.features]

CommitMono = [
  "+cv05",
  "+cv08",
  "+cv09",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
]

# CommitMono = ["+cv05", "+cv08", "+cv09", "+ss01", "+ss02"]

FiraCode = [
  "+cv01",
  "+cv02",
  "+cv14",
  "+cv24",
  "+cv27",
  "+ss01",
  "+ss06",
  "+ss07",
  "+ss08",
  "+zero",
]

# https://neovide.dev/config-file.html?highlight=box#box-drawing
[box-drawing]
mode = "native"
